# Generated by Django 2.2.5 on 2019-12-12 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.FileField(blank=True, upload_to='videos/intro', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
