export const FETCH_COURSES = "FETCH_COURSES"
export const FETCH_COURSE = "FETCH_COURSE"
export const FETCH_TOP_COURSES = "FETCH_TOP_COURSES"
export const FETCH_COURSE_SECTION_CONTENT = "FETCH_COURSE_SECTION_CONTENT"
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

export const UPDATE_COURSE = "UPDATE_COURSE"

export const NEW_COURSE = "NEW_COURSE"
export const NEW_SECTION = "NEW_SECTION"
export const NEW_CONTENT = "NEW_CONTENT"

export const DELETE_CONTENT = "DELETE_CONTENT"
export const FETCH_CONTENT = "FETCH_CONTENT"
export const UPDATE_CONTENT = "UPDATE_CONTENT"
export const INSTRUCTOR_COURSES = "INSTRUCTOR_COURSES"


export const SIGNUP = "SIGNUP"
export const SIGNIN = "SIGNIN"
export const LOGOUT = "LOGOUT"
export const USERDETAILS = "USERDETAILS"